import { ExecutionPlan } from "./types";

export function planToText(plan: ExecutionPlan, idea: string): string {
  let out = `NEUROVA EXECUTION PLAN\n`;
  out += `Generated by Neuro · AI Business Strategist\n`;
  out += `${"═".repeat(60)}\n\n`;
  out += `IDEA: ${idea}\n\n`;
  out += `TITLE: ${plan.title}\n`;
  out += `CATEGORY: ${plan.category}  |  DIFFICULTY: ${plan.difficulty}  |  DURATION: ${plan.totalDuration}\n\n`;
  out += `OVERVIEW\n${"─".repeat(40)}\n${plan.overview}\n\n`;
  out += `⚡ FIRST ACTION TODAY\n${plan.firstAction}\n\n`;

  plan.phases.forEach((phase) => {
    out += `${"═".repeat(60)}\n`;
    out += `PHASE ${phase.phase}: ${phase.name.toUpperCase()}  (${phase.duration})\n`;
    out += `${"─".repeat(40)}\n`;
    phase.steps.forEach((step) => {
      out += `  ${step.number}. [${step.priority.toUpperCase()}] ${step.title} · ${step.duration}\n`;
      out += `     ${step.description}\n\n`;
    });
  });

  out += `${"═".repeat(60)}\nTOOLS & RESOURCES\n${"─".repeat(40)}\n`;
  plan.tools.forEach((t) => {
    out += `  • ${t.name}${t.free ? " (Free)" : ""}${t.url ? `  →  ${t.url}` : ""}\n`;
    out += `    ${t.purpose}\n`;
  });

  out += `\nRISKS & MITIGATIONS\n${"─".repeat(40)}\n`;
  plan.risks.forEach((r) => {
    out += `  [${r.severity.toUpperCase()}] ${r.risk}\n`;
    out += `    ↳ ${r.mitigation}\n`;
  });

  out += `\nSUCCESS METRICS\n${"─".repeat(40)}\n`;
  plan.successMetrics.forEach((m) => { out += `  ✓ ${m}\n`; });

  out += `\n${"═".repeat(60)}\nPlan Smart. Build Real. — NEUROVA\n`;
  return out;
}

export function downloadText(plan: ExecutionPlan, idea: string): void {
  const text = planToText(plan, idea);
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `neurova-plan-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF(plan: ExecutionPlan, idea: string): void {
  const text = planToText(plan, idea);
  // Build a styled HTML page and use browser print-to-PDF
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${plan.title} — NEUROVA</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=DM+Sans:wght@300;400;500&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DM Sans', sans-serif; background: #050505; color: #F0EEFF; padding: 48px; max-width: 900px; margin: 0 auto; font-size: 13px; line-height: 1.7; }
  h1 { font-family: 'Syne', sans-serif; font-size: 28px; font-weight: 800; background: linear-gradient(135deg,#fff,#C4B5FD,#818CF8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 4px; }
  .meta { color: #9B7BFF; font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase; margin-bottom: 24px; }
  .label { font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: #22D3EE; margin-bottom: 6px; margin-top: 28px; }
  .overview { color: rgba(200,190,255,0.75); font-size: 14px; font-weight: 300; }
  .first-action { background: rgba(34,211,238,0.07); border: 1px solid rgba(34,211,238,0.2); padding: 14px 18px; border-radius: 3px; color: #F0EEFF; margin-top: 20px; font-size: 13px; }
  .phase { margin-top: 28px; border: 1px solid rgba(124,58,237,0.2); border-radius: 3px; overflow: hidden; }
  .phase-header { background: rgba(124,58,237,0.08); padding: 12px 18px; font-family: 'Syne', sans-serif; font-weight: 700; font-size: 14px; color: #C4B5FD; }
  .step { padding: 14px 18px; border-top: 1px solid rgba(124,58,237,0.1); }
  .step-title { font-weight: 500; color: #F0EEFF; margin-bottom: 4px; }
  .step-meta { font-size: 11px; color: #9B7BFF; margin-bottom: 4px; }
  .step-desc { color: rgba(200,190,255,0.65); font-weight: 300; font-size: 12px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 20px; }
  .card { border: 1px solid rgba(124,58,237,0.15); border-radius: 3px; padding: 16px; }
  .card-title { font-family: 'Syne', sans-serif; font-size: 12px; letter-spacing: 0.12em; text-transform: uppercase; color: #9B7BFF; margin-bottom: 12px; }
  .tool { margin-bottom: 10px; }
  .tool-name { font-weight: 500; color: #F0EEFF; font-size: 12px; }
  .tool-desc { color: rgba(200,190,255,0.55); font-size: 11px; }
  .risk { margin-bottom: 10px; }
  .risk-label { font-weight: 500; color: #F0EEFF; font-size: 12px; }
  .risk-mit { color: rgba(200,190,255,0.55); font-size: 11px; }
  .metric { display: flex; align-items: flex-start; gap: 8px; margin-bottom: 6px; color: rgba(200,190,255,0.7); font-size: 12px; }
  .metric::before { content: "✓"; color: #9B7BFF; flex-shrink: 0; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid rgba(124,58,237,0.15); text-align: center; color: rgba(160,150,210,0.4); font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; }
  @media print { body { padding: 24px; } }
</style>
</head>
<body>
  <h1>${plan.title}</h1>
  <div class="meta">${plan.category} · ${plan.difficulty} · ${plan.totalDuration}</div>
  <div class="label">Overview</div>
  <div class="overview">${plan.overview}</div>
  <div class="first-action">⚡ <strong>First Action Today:</strong> ${plan.firstAction}</div>
  ${plan.phases.map(phase => `
  <div class="phase">
    <div class="phase-header">Phase ${phase.phase} — ${phase.name} <span style="font-weight:300;font-size:12px;color:rgba(155,123,255,0.7)">(${phase.duration})</span></div>
    ${phase.steps.map(step => `
    <div class="step">
      <div class="step-meta">${step.number}. [${step.priority.toUpperCase()}] · ${step.duration}</div>
      <div class="step-title">${step.title}</div>
      <div class="step-desc">${step.description}</div>
    </div>`).join("")}
  </div>`).join("")}
  <div class="grid">
    <div class="card">
      <div class="card-title">Tools & Resources</div>
      ${plan.tools.map(t => `<div class="tool"><div class="tool-name">${t.name}${t.free ? ' <span style="color:#86EFAC;font-size:10px">(Free)</span>' : ''}</div><div class="tool-desc">${t.purpose}</div></div>`).join("")}
    </div>
    <div class="card">
      <div class="card-title">Risks & Mitigations</div>
      ${plan.risks.map(r => `<div class="risk"><div class="risk-label">[${r.severity.toUpperCase()}] ${r.risk}</div><div class="risk-mit">↳ ${r.mitigation}</div></div>`).join("")}
    </div>
  </div>
  <div class="label" style="margin-top:24px">Success Metrics</div>
  <div class="card" style="margin-top:8px">
    ${plan.successMetrics.map(m => `<div class="metric">${m}</div>`).join("")}
  </div>
  <div class="footer">Plan Smart. Build Real. — NEUROVA · Generated by Neuro AI</div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.onload = () => { win.print(); };
}
